n1 = float(input('Digite um valor: '))
n2 = int(input('Digite outro: '))
n3 = bool(input('E outro: '))
n4 = input('Digite algo: ')
print(n1)
print(n2)
print(n3)
print(n4)
print(type(n4))
print(n4.isalpha())
print(n4.isalnum())
print(n4.isnumeric())
print(n4.islower())
print(n4.isupper())
print(n4.istitle())
